name: Bootstrap a new account in access-control repo
description: "Sets up a new AWS account and basic roles inside the access control repo"
inputs:
  terragrunt_command:
    description: "The name of the configured deploy branch"
    required: false
    default: main
  new_account_name:
    description: ""
    required: true

runs:
  using: composite
  steps:
    - name: "[ProvisionDelegatedAccount]: Read account request"
      id: bootstrap
      uses: gruntwork-io-team/pipelines-bootstrap@main
      with:
        new_account_name: ${{ inputs.new_account_name }}
        terragrunt_command: ${{ inputs.terragrunt_command }}

    - name: "[Baseline]: Authenticate to Security AWS account"
      if: steps.bootstrap.outputs.workflow == 'apply-new-account-baseline.yml'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: "arn:aws:iam::${{ steps.bootstrap.outputs.security_account_id }}:role/${{ steps.bootstrap.outputs.role_name }}"
        role-duration-seconds: 3600
        role-session-name: ${{ steps.bootstrap.outputs.role_session_name }}

    - name: "[Baseline]: Run terragrunt ${{ steps.bootstrap.outputs.terragrunt_command }} in security account"
      id: terragrunt-apply-security
      if: steps.bootstrap.outputs.workflow == 'apply-new-account-baseline.yml'
      uses: gruntwork-io/pipelines-execute@v3.0.0
      with:
        token: ${{ secrets.GRUNTWORK_CODE_ACCESS_TOKEN }}
        tf_version: ${{ steps.bootstrap.outputs.terraform_version }}
        tg_version: ${{ steps.bootstrap.outputs.terragrunt_version }}
        pipelines_cli_version: ${{ steps.bootstrap.outputs.pipelines_cli_version }}
        working_directory: security/_global/account-baseline
        terragrunt_command: "${{ steps.bootstrap.outputs.terragrunt_command }}"
        infra_live_repo: '.'
        infra_live_directory: '.'
        infra_live_repo_branch: ${{ steps.bootstrap.outputs.branch }}
        gruntwork_config: "${{ steps.bootstrap.outputs.gruntwork_config }}"

    - name: "[Baseline]: Authenticate to Logs AWS account"
      if: steps.bootstrap.outputs.workflow == 'apply-new-account-baseline.yml'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: "arn:aws:iam::${{ steps.bootstrap.outputs.logs_account_id }}:role/${{ steps.bootstrap.outputs.role_name }}"
        role-duration-seconds: 3600
        role-session-name: ${{ steps.bootstrap.outputs.role_session_name }}

    - name: "[Baseline]: Run terragrunt ${{ steps.bootstrap.outputs.terragrunt_command }} in logs account"
      id: terragrunt-apply-logs
      if: steps.bootstrap.outputs.workflow == 'apply-new-account-baseline.yml'
      uses: gruntwork-io/pipelines-execute@v3.0.0
      with:
        token: ${{ secrets.GRUNTWORK_CODE_ACCESS_TOKEN }}
        tf_version: ${{ steps.bootstrap.outputs.terraform_version }}
        tg_version: ${{ steps.bootstrap.outputs.terragrunt_version }}
        pipelines_cli_version: ${{ steps.bootstrap.outputs.pipelines_cli_version }}
        working_directory: logs/_global/account-baseline
        terragrunt_command: "${{ steps.bootstrap.outputs.terragrunt_command }}"
        infra_live_repo: '.'
        infra_live_directory: '.'
        infra_live_repo_branch: ${{ steps.bootstrap.outputs.branch }}
        gruntwork_config: "${{ steps.bootstrap.outputs.gruntwork_config }}"

    - name: "[Baseline]: Authenticate to Shared Services AWS account"
      if: steps.bootstrap.outputs.workflow == 'apply-new-account-baseline.yml'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: "arn:aws:iam::${{ steps.bootstrap.outputs.shared_account_id }}:role/${{ steps.bootstrap.outputs.role_name }}"
        role-duration-seconds: 3600
        role-session-name: ${{ steps.bootstrap.outputs.role_session_name }}

    - name: "[Baseline]: Run terragrunt ${{ steps.bootstrap.outputs.terragrunt_command }} in shared account"
      id: terragrunt-apply-shared
      if: steps.bootstrap.outputs.workflow == 'apply-new-account-baseline.yml'
      uses: gruntwork-io/pipelines-execute@v3.0.0
      with:
        token: ${{ secrets.GRUNTWORK_CODE_ACCESS_TOKEN }}
        tf_version: ${{ steps.bootstrap.outputs.terraform_version }}
        tg_version: ${{ steps.bootstrap.outputs.terragrunt_version }}
        pipelines_cli_version: ${{ steps.bootstrap.outputs.pipelines_cli_version }}
        working_directory: shared/_global/account-baseline
        terragrunt_command: "${{ steps.bootstrap.outputs.terragrunt_command }}"
        infra_live_repo: '.'
        infra_live_directory: '.'
        infra_live_repo_branch: ${{ steps.bootstrap.outputs.branch }}
        gruntwork_config: "${{ steps.bootstrap.outputs.gruntwork_config }}"

    # Finally, auth to the mgmt account so we can assume a role in the child account
    - name: "[Baseline]: Authenticate to AWS"
      if: steps.bootstrap.outputs.workflow == 'apply-new-account-baseline.yml'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: "arn:aws:iam::${{ steps.bootstrap.outputs.account_id }}:role/${{ steps.bootstrap.outputs.role_name }}"
        role-duration-seconds: 3600
        role-session-name: ${{ steps.bootstrap.outputs.role_session_name }}

    # Auth to child account
    # THIS RETRIEVES PERMISSIONS TO BE ABLE TO RUN A PLAN/APPLY IN THE NEWLY CREATED CHILD ACCOUNT
    # The "AWSControlTowerExecution" role being assumed here is created by Control Tower in each account it provisions
    # and it can be assumed by a role in the management account.
    - name: "[Baseline]: Assume role new child account"
      shell: bash
      if: steps.bootstrap.outputs.workflow == 'apply-new-account-baseline.yml'
      env:
        SESSION_NAME: ${{ steps.bootstrap.outputs.role_session_name }}
        CHILD_ACCOUNT: ${{ steps.bootstrap.outputs.child_account_id }}
      run: |
        RESPONSE="$(aws sts assume-role --role-arn "arn:aws:iam::$CHILD_ACCOUNT:role/AWSControlTowerExecution" --role-session-name "$SESSION_NAME")"
        ASSUMED_ROLE_CREDS="$(echo "$RESPONSE" | jq -r '.Credentials')"
        AWS_ACCESS_KEY_ID="$(echo "$ASSUMED_ROLE_CREDS" | jq -r '.AccessKeyId')"
        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> "$GITHUB_ENV"
        echo "::add-mask::$AWS_ACCESS_KEY_ID"
        AWS_SECRET_ACCESS_KEY="$(echo "$ASSUMED_ROLE_CREDS" | jq -r '.SecretAccessKey')"
        echo AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" >> "$GITHUB_ENV"
        echo "::add-mask::$AWS_SECRET_ACCESS_KEY"
        AWS_SESSION_TOKEN="$(echo "$ASSUMED_ROLE_CREDS" | jq -r '.SessionToken')"
        echo AWS_SESSION_TOKEN="$AWS_SESSION_TOKEN" >> "$GITHUB_ENV"
        echo "::add-mask::$AWS_SESSION_TOKEN"

    - name: "[Baseline]: Confirm Account Access"
      if: steps.bootstrap.outputs.workflow == 'apply-new-account-baseline.yml'
      shell: bash
      env:
        CHILD_ACCOUNT: ${{ steps.bootstrap.outputs.child_account_id }}
        WORKING_DIRECTORY: ${{ steps.bootstrap.outputs.working_directory }}
      run: echo "::notice ::Running in account $CHILD_ACCOUNT and planning in $WORKING_DIRECTORY"

    # This Bootstrap step is a workaround for the error that happens when running plan-all for the first time in a
    # new account with multiple modules. The error is:
    #
    #    OperationAborted: A conflicting conditional operation is currently in progress against this resource. Please try again.
    #    BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
    #
    # This happens because each module is trying to create buckets for state and logs when they do not exist.
    # Setting Terragrunt Parallelism to 1 does NOT prevent this error from happening. So we'll instead run an init in
    # a single module first to create the buckets so that subsequent run-all commands do not fail.
    - name: "[Baseline]: Bootstrap child account with state & logs S3 buckets"
      if: ${{ contains(steps.bootstrap.outputs.terragrunt_command, 'plan') && steps.bootstrap.outputs.workflow == 'apply-new-account-baseline.yml' }}
      uses: gruntwork-io/pipelines-execute@v3.0.0
      with:
        token: ${{ secrets.GRUNTWORK_CODE_ACCESS_TOKEN }}
        tf_version: ${{ steps.bootstrap.outputs.terraform_version }}
        tg_version: ${{ steps.bootstrap.outputs.terragrunt_version }}
        pipelines_cli_version: ${{ steps.bootstrap.outputs.pipelines_cli_version }}
        working_directory: "${{ steps.bootstrap.outputs.working_directory }}/_global/account-baseline"
        terragrunt_command: "init"
        infra_live_repo: '.'
        infra_live_directory: '.'
        infra_live_repo_branch: ${{ steps.bootstrap.outputs.branch }}
        gruntwork_config: "${{ steps.bootstrap.outputs.gruntwork_config }}"
